language: go
go:
  - 1.4

script:
  - go test -v
  - go install -v
after_success:
  - tar -C $HOME/gopath/bin -vzcf /tmp/4d_linux_amd64.tar.gz 4d

deploy:
  provider: releases
  api_key:
    secure: TM+NFPZr3tiVOwxkbc3QZdJysrXwBw6hOMWuGvTMR9tacSlVmO6/93Wg8mdeo13sr+nGDUkb4YWrIsELT3w2e4W2P6cEMyIuSywFyEm9bG/9MQc0T28P3sTncWzsGzCzMs3lrOdeIuncjyzyV9hpXvl8Z4qYUlGuQqitjkJkGak=
  file: /tmp/4d_linux_amd64.tar.gz
  on:
    tags: true
