language: go
go:
- tip
script:
- go test -v
- go install -v
after_success:
- tar -C $HOME/gopath/bin -vzcf /tmp/4d_linux_amd64.tar.gz 4d
deploy:
  provider: releases
  api_key:
    secure: 1wPlm8hmeIzwxSujAbN4E/1sCMaC8Mzo5GVRCRnmwtuhz+YszS1UJdeUwDmrOHjWrpGnGu5W01SD7ZtZxBmTVRno4R0lX7ghJ4sGAelPyXrcpBwWmkOyayrq1RyohUVe9Uk9vDny9fgkyNYxgUkUpen9DZMwXt1Sz9+o36ays6Y=
  on:
    tags: true
