language: go
go:
  - 1.x

env:
  - GOOS=linux   GOARCH=386
  - GOOS=linux   GOARCH=amd64
  - GOOS=linux   GOARCH=arm
  - GOOS=linux   GOARCH=arm64
  - GOOS=linux   GOARCH=mips  GOMIPS=softfloat

  - GOOS=darwin  GOARCH=amd64
  - GOOS=windows GOARCH=amd64

  - GOOS=freebsd GOARCH=amd64
  - GOOS=openbsd GOARCH=amd64
  - GOOS=plan9   GOARCH=amd64

script:
  - go test -v ./...
  - export FNAME=4d_${TRAVIS_TAG}_${GOOS}_${GOARCH}
  - go build -o ${FNAME}
  - tar -vzcf ${FNAME}.tgz ${FNAME}

after_success: []
deploy:
  provider: releases
  api_key:
    secure: X6ihaSrHeeCunRzgOxKyfKq3063OXDT96cnwdXk/f37YXtEZM7FyC32hiAsUU9+0yfvxkBZsgaKFUk5aEpzFt5NK/fbSiCULIwaZh434HAiFNhLE/IjHyBtOp0D0m5kt6SwhP1fyr1iRS4aDfT30GgvOgDn8cjHDwafjnEGFFxQ=
  skip_cleanup: true
  file_glob: true
  file: *.tgz
  on:
    tags: true
