language: go
go:
- 1.x
- master
script:
- go test -v
- go install -v
after_success:
- tar -C $HOME/gopath/bin -vzcf /tmp/4d_linux_amd64.tar.gz 4d
deploy:
  provider: releases
  api_key:
    secure: X6ihaSrHeeCunRzgOxKyfKq3063OXDT96cnwdXk/f37YXtEZM7FyC32hiAsUU9+0yfvxkBZsgaKFUk5aEpzFt5NK/fbSiCULIwaZh434HAiFNhLE/IjHyBtOp0D0m5kt6SwhP1fyr1iRS4aDfT30GgvOgDn8cjHDwafjnEGFFxQ=
  file: /tmp/4d_linux_amd64.tar.gz
  on:
    tags: true
