language: go
go:
- 1.x
env:
  - APP=4d
  - FPREFIX=${APP}_${TRAVIS_TAG}
script:
- go test -v
- GOARCH=amd64 go build -o ${FPREFIX}_amd64
- GOARCH=arm go build -o ${FPREFIX}_arm
- GOARCH=mips GOMIPS=softfloat go build -o ${FPREFIX}_mipsSF
- mv ${APP}* /tmp
after_success:
- cd /tmp
- tar -vzcf ${FPREFIX}_linux_amd64.tgz ${FPREFIX}_amd64
- tar -vzcf ${FPREFIX}_linux_arm.tgz ${FPREFIX}_arm
- tar -vzcf ${FPREFIX}_linux_mips_softfloat.tgz ${FPREFIX}_mipsSF
deploy:
  provider: releases
  api_key:
    secure: X6ihaSrHeeCunRzgOxKyfKq3063OXDT96cnwdXk/f37YXtEZM7FyC32hiAsUU9+0yfvxkBZsgaKFUk5aEpzFt5NK/fbSiCULIwaZh434HAiFNhLE/IjHyBtOp0D0m5kt6SwhP1fyr1iRS4aDfT30GgvOgDn8cjHDwafjnEGFFxQ=
  file:
    - /tmp/${FPREFIX}_linux_amd64.tgz
    - /tmp/${FPREFIX}_linux_arm.tgz
    - /tmp/${FPREFIX}_linux_mipsSF.tgz
  on:
    tags: true
